name: CI Pipeline - Backend & Frontend

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub using GitHub Secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Backend Image
      - name: Build & Push Backend
        run: |
          docker build -t prachiiy258/backend:v1 ./backend
          docker push prachiiy258/backend:v1

      # Step 4: Build & Push Frontend Image
      - name: Build & Push Frontend
        run: |
          docker build -t prachiiy258/frontend:v1 ./frontend
          docker push prachiiy258/frontend:v1
