name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub using GitHub Secrets
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build backend Docker image
      - name: Build Backend Image
        run: docker build -t prachiiy258/backend:v1 ./backend

      # Step 4: Push backend Docker image
      - name: Push Backend Image
        run: docker push prachiiy258/backend:v1

      # Step 5: Build frontend Docker image
      - name: Build Frontend Image
        run: docker build -t prachiiy258/frontend:v1 ./frontend

      # Step 6: Push frontend Docker image
      - name: Push Frontend Image
        run: docker push prachiiy258/frontend:v1
