name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to DockerHub using GitHub secrets
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build backend Docker image
      - name: Build Backend Image
        run: docker build -t prachiiy258/backend:v1 ./backend

      # Push backend Docker image
      - name: Push Backend Image
        run: docker push prachiiy258/backend:v1

      # Build frontend Docker image
      - name: Build Frontend Image
        run: docker build -t prachiiy258/frontend:v1 ./frontend

      # Push frontend Docker image
      - name: Push Frontend Image
        run: docker push prachiiy258/frontend:v1
